FROM node:20-alpine

RUN mkdir /app
COPY . /app
WORKDIR /app

RUN yarn install --network-timeout 100000 

# Add dependencies for hot reloading
RUN yarn add react-hot-loader

# Configure hot reloading
ENV CHOKIDAR_USEPOLLING=true

EXPOSE 3000
