import {
  ArrowDown01Icon,
  ArrowDownAZIcon,
  ArrowUp10Icon,
  ArrowUpZAIcon,
  CalendarClock,
  ChevronLeftCircle,
  ChevronRightCircle,
  HomeIcon,
  MailIcon,
  MarsIcon,
  PanelLeftCloseIcon,
  PanelLeftOpenIcon,
  PhoneIcon,
  RulerIcon,
  SettingsIcon,
  SquarePenIcon,
  TrashIcon,
  UserIcon,
  UsersIcon,
  VenusIcon,
  WeightIcon,
} from 'lucide-react'

export const icons = {
  sortAscNumber: <ArrowDown01Icon />,
  sortDescNumber: <ArrowUp10Icon />,
  sortAscAlpha: <ArrowDownAZIcon />,
  sortDescAlpha: <ArrowUpZAIcon />,
  next: <ChevronRightCircle />,
  prev: <ChevronLeftCircle />,
  settings: <SettingsIcon />,
  home: <HomeIcon />,
  calendar: <CalendarClock />,
  sidebarOpen: <PanelLeftOpenIcon />,
  sidebarClose: <PanelLeftCloseIcon />,
  patient: <UserIcon />,
  patients: <UsersIcon />,
  email: <MailIcon />,
  phone: <PhoneIcon />,
  male: <MarsIcon />,
  female: <VenusIcon />,
  height: <RulerIcon />,
  weight: <WeightIcon />,
  edit: <SquarePenIcon />,
  delete: <TrashIcon />,
}
